### ISSUE TITLE
Error loading with the Panda Loader on Windows

### ISSUE THREAD

**Issue by thetestgame** [Moguri/blend2bam#37]
There appears to be a file path issue with the temp file used by the loading process.

```
:express(warning): Filename uses Windows-style path: C:\Users\nxtla\AppData\Local\Temp\tmpb74tu0dg.bam
:express(warning):   expected Unix-style path: /c/Users/nxtla/AppData/Local/Temp/tmpb74tu0dg.bam
:express(warning): Filename uses Windows-style path: C:\Users\nxtla\AppData\Local\Temp\tmpb74tu0dg.bam
:express(warning):   expected Unix-style path: /c/Users/nxtla/AppData/Local/Temp/tmpb74tu0dg.bam
:loader(error): Couldn't load file C:\Users\nxtla\AppData\Local\Temp\tmpb74tu0dg.bam: does not exist.
:loader(error): load_file must return valid PandaNode or raise exception
:loader(error): Couldn't load file test.blend: all matching files on model path invalid (the model path is currently: "/c/Users/nxtla/AppData/Local/Temp;/c/Users/nxtla/AppData/Local/Temp;/d/dev/Nxt Games/CaptureThePacket;/c/Users/nxtla/AppData/Local/Programs/Python/Python38-32/Lib/site-packages/panda3d/etc/..;/c/Users/nxtla/AppData/Local/Programs/Python/Python38-32/Lib/site-packages/panda3d/etc/../models")
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    test  = loader.load_model('test.blend')
  File "C:\Users\nxtla\AppData\Local\Programs\Python\Python38-32\lib\site-packages\direct\showbase\Loader.py", line 298, in loadModel
    raise IOError(message)
OSError: Could not load model file(s): ['test.blend']
```

**Comment by rdb** [comment]
Can confirm; loading via the Panda loader is currently not working on Windows for this reason (and separately also because of #38).
