### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Germanunkol** [Moguri/blend2bam#66]
I've gotten the following IndexError a few times now.
It looks like it has to do with a bunch of objects which are part of the RigidBodyWorld collection. When I delete that collection, it works.
However, I'm not quite sure - sometimes it even works with the RigidBodyWorld collection still in place.

I can try to provide a minimal example if needed, just don't have the time right now and wanted to leave this here.

```
Blender 2.93.4 (hash b7205031cec4 built 2021-08-31 23:43:17)
Read prefs: /home/micha/.config/blender/2.93/config/userpref.blend
srcroot: /home/micha/Projects/ProceduralCave/
Exporting: ['/home/micha/Projects/ProceduralCave/ProceduralCave.blend']
Export to: /tmp/
Read blend: /home/micha/Projects/ProceduralCave/ProceduralCave.blend
Converting .blend file (/home/micha/Projects/ProceduralCave/ProceduralCave.blend) to .gltf (/tmp/ProceduralCave.gltf)
'/home/micha/Software/blender-2.93.4-linux-x64/2.93/python/lib/python3.9/site-packages/libextern_draco.so' exists, draco mesh compression is available
22:11:12 | INFO: Starting glTF 2.0 export
22:11:12 | INFO: Extracting primitive: Ground
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.001
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.002
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.003
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.004
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.005
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.006
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.007
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.008
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.009
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.010
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.011
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.012
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.013
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.014
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.015
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.016
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.017
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.018
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.019
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.020
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.021
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.022
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.023
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.024
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.025
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.026
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.027
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.028
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.029
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.030
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.031
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.032
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.033
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.034
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.035
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.036
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.037
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.038
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.039
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.040
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.041
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.042
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.043
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.044
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.045
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.046
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.047
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.048
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.049
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.050
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.051
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.052
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.053
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.054
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.055
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.056
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.057
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.058
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.059
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.060
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_collision.061
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: Ground_collision.001
22:11:12 | INFO: Primitives created: 1
22:11:12 | INFO: Extracting primitive: CaveSystem_rocks
Error: Tangent space can only be computed for tris/quads, aborting
22:11:12 | WARNING: Could not calculate tangents. Please try to triangulate the mesh first.
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: Kinfe
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.002
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.003
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.004
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.005
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.006
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.007
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.008
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.009
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.010
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.011
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.012
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.013
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.014
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.015
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.016
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.017
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.018
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.019
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.020
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.021
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.022
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.023
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.024
Error: Tangent space can only be computed for tris/quads, aborting
22:11:13 | WARNING: Could not calculate tangents. Please try to triangulate the mesh first.
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.025
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.026
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.027
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.028
22:11:13 | INFO: Primitives created: 2
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.029
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.030
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.031
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.032
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.033
22:11:13 | INFO: Primitives created: 1
22:11:13 | INFO: Extracting primitive: CaveSystem_rocks_section.034
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.035
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.036
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.037
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.038
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.039
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.040
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.041
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.042
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.043
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.044
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.045
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.046
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.047
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.048
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.049
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.050
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.051
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.052
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.053
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.054
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.055
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.056
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.057
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.058
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.059
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.060
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.061
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section.001
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Extracting primitive: CaveSystem_rocks_section
22:11:14 | INFO: Primitives created: 1
22:11:14 | INFO: Extracting primitive: Corridors
22:11:14 | INFO: Primitives created: 0
22:11:14 | WARNING: Mesh 'Corridors' has no primitives and will be omitted.
22:11:14 | INFO: Extracting primitive: CaveSystem
22:11:14 | INFO: Primitives created: 2
22:11:14 | INFO: Finished glTF 2.0 export in 1.9887375831604004 s

Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blend2gltf/../blender_script_common.py", line 32, in convert_files
    convertfn(settings, src, dst)
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blend2gltf/blender28_script.py", line 178, in export_gltf
    export_physics(gltf_data)
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blend2gltf/blender28_script.py", line 35, in export_physics
    meshref = [
IndexError: list index out of range
Failed to convert /home/micha/Projects/ProceduralCave/ProceduralCave.blend to gltf
Traceback (most recent call last):
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/cli.py", line 88, in convert
    src2tmp.convert_single(srcfile, tmpfile.name)
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blend2gltf/__init__.py", line 46, in convert_single
    self.convert_batch(srcroot, dstdir, files)
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blend2gltf/__init__.py", line 61, in convert_batch
    blenderutils.run_blender_script(self.script_file, args, blenderdir=blenderdir)
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blenderutils.py", line 33, in run_blender_script
    blenderbin=blenderbin
  File "/home/micha/.local/lib/python3.6/site-packages/blend2bam/blenderutils.py", line 23, in run_blender
    subprocess.check_call([binpath, '--background'] + args, stdout=None)#subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/micha/Software/blender-2.93.4-linux-x64/blender', '--background', '-P', '/home/micha/.local/lib/python3.6/site-packages/blend2bam/blend2gltf/blender28_script.py', '--', '/tmp/tmp3xgy6c4y', '/home/micha/Projects/ProceduralCave', '/tmp', '/home/micha/Projects/ProceduralCave/ProceduralCave.blend']' returned non-zero exit status 1.

Failed to convert all files
'/home/micha/Projects/ProceduralCave/cluster_centers.pickle' -> './cluster_centers.pickle'
'/home/micha/Projects/ProceduralCave/navmesh.pickle' -> './navmesh.pickle'
'/home/micha/Projects/ProceduralCave/verts_to_clusters_per_object.pickle' -> './verts_to_clusters_per_object.pickle'
'/home/micha/Projects/ProceduralCave/verts_to_clusters.pickle' -> './verts_to_clusters.pickle'
```

**Comment by Moguri** [comment]
I will need some way to repro this. A blend file I can run locally would work the best. If you *can* simplify it, that would be ideal, but, if not, that still gives me something to play with.

**Comment by Moguri** [comment]
Closing due to lack of response and no repro. Feel free to reopen this if/when you are able to get a repro case together.
