### ISSUE TITLE
blend file with box collision shape on a 0 height plane causes crash

### ISSUE THREAD

**Issue by william-lohan** [Moguri/blend2bam#81]
# error

> AssertionError: _v(0) != 0.0f at line 44 of panda/src/mathutil/plane_src.cxx

# steps
- clone https://github.com/william-lohan/my-panda-py/tree/blend2bam_issues 
- run `blend2bam ./models/floor.blend ./models/floor.bam`

> Blender 3.5.1 (hash 6ee8aa4997ee built 2023-05-06 00:20:19)
Read prefs: /home/will/.config/blender/3.5/config/userpref.blend
Failed to open dir (No such file or directory): /run/user/1000/gvfs/
Reloading external rigs...
Reloading external metarigs...
Read blend: /home/will/source/my-panda-py/models/floor.blend

> Blender quit
Assertion failed: _v(0) != 0.0f at line 44 of panda/src/mathutil/plane_src.cxx
Assertion failed: _v(0) != 0.0f at line 44 of panda/src/mathutil/plane_src.cxx
Assertion failed: _v(0) != 0.0f at line 44 of panda/src/mathutil/plane_src.cxx
Assertion failed: _v(0) != 0.0f at line 44 of panda/src/mathutil/plane_src.cxx
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.11/site-packages/blend2bam/cli.py", line 89, in convert
    tmp2dst.convert_single(tmpfile.name, dst)
  File "/home/will/.local/lib/python3.11/site-packages/blend2bam/gltf2bam.py", line 62, in convert_single
    run_gltf2bam(src, dst, self.cli_args)
  File "/home/will/.local/lib/python3.11/site-packages/blend2bam/gltf2bam.py", line 26, in run_gltf2bam
    runpy.run_module('gltf.cli', run_name='__main__', alter_sys=True)
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/will/.local/lib/python3.11/site-packages/gltf/cli.py", line 156, in <module>
    main()
  File "/home/will/.local/lib/python3.11/site-packages/gltf/cli.py", line 121, in main
    converter.update(gltf_data)
  File "/home/will/.local/lib/python3.11/site-packages/gltf/converter.py", line 436, in update
    add_node(scene_root, gltf_scene, nodeid)
  File "/home/will/.local/lib/python3.11/site-packages/gltf/converter.py", line 364, in add_node
    phynode = self.load_physics_builtin(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/will/.local/lib/python3.11/site-packages/gltf/converter.py", line 1817, in load_physics_builtin
    solids.append(CollisionBox(Point3(0, 0, 0), *LVector3(*bounding_box) / 2.0))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: _v(0) != 0.0f at line 44 of panda/src/mathutil/plane_src.cxx

> Failed to convert all files

**Comment by william-lohan** [comment]
moved to Moguri/panda3d-gltf#122
