### ISSUE TITLE
get_blender_version fails to parse output

### ISSUE THREAD

**Issue by nate-byrnes** [Moguri/blend2bam#95]
Trying to use blend2bam with blender 3.0.1, but it looks like there's extra output from blender that breaks version checking

```
$ blender --version
Color management: using fallback mode for management
Color management: Error could not find role data role.
Blender 3.0.1
```

calling blend2bam results in:

```
Traceback (most recent call last):
  File "/home/nate/Desktop/Dev/NoRD/.venv/bin/blend2bam", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nate/Desktop/Dev/NoRD/.venv/lib/python3.12/site-packages/blend2bam/cli.py", line 192, in main
    if not args.blender_dir and not blenderutils.blender_exists():
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nate/Desktop/Dev/NoRD/.venv/lib/python3.12/site-packages/blend2bam/blenderutils.py", line 48, in blender_exists
    is_blender_28(blenderdir=blenderdir, blenderbin=blenderbin)
  File "/home/nate/Desktop/Dev/NoRD/.venv/lib/python3.12/site-packages/blend2bam/blenderutils.py", line 66, in is_blender_28
    version = get_blender_version(blenderdir=blenderdir, blenderbin=blenderbin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nate/Desktop/Dev/NoRD/.venv/lib/python3.12/site-packages/blend2bam/blenderutils.py", line 60, in get_blender_version
    version = [int(i) for i in output.split()[1].split('.')]
               ^^^^^^
ValueError: invalid literal for int() with base 10: 'management:'
```

**Comment by nate-byrnes** [comment]
This is ubuntu 22.04 LTS desktop default install of blender
